export const sagaActions = {
  USER_SIGNUP_SAGA: 'USER_SIGNUP_SAGA',
  USER_LOGIN_SAGA: 'USER_LOGIN_SAGA',
  USER_LOGOUT_SAGA: 'USER_LOGOUT_SAGA',
  USER_REFRESH_SAGA: 'USER_REFRESH_SAGA',
  USER_RESET_SAGA: 'USER_RESET_SAGA',
  USER_NEWPASS_SAGA: 'USER_NEWPASS_SAGA',
  USER_UPDATE_DATA_SAGA: 'USER_UPDATE_DATA_SAGA',
  USER_GET_AVATAR_SAGA: 'USER_GET_AVATAR_SAGA',
  USER_GET_DATA_SAGA: 'USER_GET_DATA_SAGA',
  USER_ADD_CAR_SAGA: 'USER_ADD_CAR_SAGA',
  USER_DELETE_CAR_SAGA: 'USER_DELETE_CAR_SAGA',
  USER_GET_CARS_SAGA: 'USER_GET_CARS_SAGA',
  USER_REGISTER_FOR_EVENT_SAGA: 'USER_REGISTER_FOR_EVENT_SAGA',
  USER_EVENTS_DATA_SAGA: 'USER_EVENTS_DATA_SAGA',
}

export const eventActions = {
  EVENT_ADD_SAGA: 'EVENT_ADD_SAGA',
  EVENT_REMOVE_SAGA: 'EVENT_REMOVE_SAGA',
  EVENT_UPDATE_SAGA: 'EVENT_UPDATE_SAGA',
  EVENT_GET_SAGA: 'EVENT_GET_SAGA',
  EVENT_SET_ID_SAGA: 'EVENT_SET_ID_SAGA',
}
