export const sagaActions = {
  USER_SIGNUP_SAGA: 'USER_SIGNUP_SAGA',
  USER_LOGIN_SAGA: 'USER_LOGIN_SAGA',
  USER_LOGOUT_SAGA: 'USER_LOGOUT_SAGA',
  USER_REFRESH_SAGA: 'USER_REFRESH_SAGA',
  USER_RESET_SAGA: 'USER_RESET_SAGA',
  USER_NEWPASS_SAGA: 'USER_NEWPASS_SAGA',
  USER_UPDATE_SAGA: 'USER_UPDATE_SAGA',
}
